title: "Kankakee Community College"
site_name: Continuing Education
public-url: "https://continuinged.kcc.edu"
url: "https://continuinged.kcc.edu"
theme: "kcc-gem-theme"
google-tag_key: GTM-K5WFF74
# BUILD
nav_config:
  smaller_brand: true
nav_links:
  - link_text: Training
    link_href: training
    button: false
  - link_text: Career Services
    link_href: career-services
    button: false
  - link_text: Facilities
    link_href: facilities
    button: false
  - link_text: About
    link_href: about
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
  - link_text: Sign&nbsp;Up/Login
    link_href: https://www.enrole.com/kcc/jsp/login.jsp
    button: true
    external: true
collections:
  announcements:
    output: false
  contacts:
    output: false
  testimonials:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "gulp-tasks/"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "/assets/adobe/"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
