title: "Kankakee Community College"
site_name: Continuing Education
public-url: "https://www.kcc.edu"
url: "https://www.kcc.edu/continuinged"
canonical_baseurl: https://www.kcc.edu/continuinged
subsection_title: "KCC Continuing Education"
theme: "kcc-gem-theme"
port: 3000
core_site: false
theme_config: false
# BUILD
timezone: America/Chicago
google-tag_key: GTM-TNVWT2L
nav_config:
  smaller_brand: true
nav_links:
  - link_text: Training
    link_href: training
    button: false
  - link_text: Facilities
    link_href: facilities
    button: false
  - link_text: About
    link_href: about
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
  - link_text: Sign&nbsp;Up/Login
    link_href: https://www.enrole.com/kcc/jsp/login.jsp
    button: true
    external: true
collections:
  announcements:
    output: false
  contacts:
    output: false
  testimonials:
    output: false
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "siteicon.png"
  - "buildtools/"
  - "postcss.config.js"
  - "look-for-deprecated-bs4-classes.mjs"
  - "look-for-deprecated-bs4-js.mjs"
  - "look-for-string-in-project-files.mjs"

uploads_dir: "uploads/" # specifies the default uploads directory for CloudCannon

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
  content:
    format: p h2 h3 h4 h5 h6 pre address div
    bold: true
    italic: true
    underline: true
    subscript: true
    superscript: true
    indent: true
    outdent: true
    image: true
    table: true
    left: align-left
    center: center-this-text
    right: align-right
    removeformat: true
    link: true
    numberedlist: true
    bulletedlist: true
    undo: true
    redo: true
    styles: /assets/css/content.css
